name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r healthy-meal-finder/requirements.txt
          pip install pytest pytest-cov openapi-spec-validator

      - name: Run pytest with coverage
        run: |
          mkdir -p reports
          pytest healthy-meal-finder/ --cov=healthy-meal-finder --cov-report=html:reports --cov-report=term --maxfail=1 --disable-warnings -q

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: reports/index.html

      - name: Validate OpenAPI schema
        run: |
          python -m pip install requests
          python -m pip install uvicorn fastapi
          uvicorn healthy-meal-finder.main:app --host 127.0.0.1 --port 8000 &
          sleep 10
          python -c "import requests; from openapi_spec_validator import validate_spec; resp = requests.get('http://127.0.0.1:8000/openapi.json'); resp.raise_for_status(); validate_spec(resp.json())" 